const Events = {
    RESIZE: 'RESIZE',
    CHANGE_STATE: 'CHANGE_STATE',

    SPAWN_DEFENDER: 'SPAWN_DEFENDER',

    UPDATE_STATS: 'UPDATE_STATS',
    UPDATE_COINS: 'UPDATE_COINS',
    UPDATE_LIVES: 'UPDATE_LIVES',
};

export default Events;