const Events = {
    RESIZE: 'RESIZE',
    CHANGE_STATE: 'CHANGE_STATE',

    SPAWN_DEFENDER: 'SPAWN_DEFENDER',
    DESTROY_DEFENDER: 'DESTROY_DEFENDER',
    SELL_DEFENDER: 'SELL_DEFENDER',
    DEFENDER_COOLDOWN_START: 'DEFENDER_COOLDOWN_START',
    DEFENDER_COOLDOWN_COMPLETE: 'DEFENDER_COOLDOWN_COMPLETE',
    HIDE_DEFENDER_MENU: 'HIDE_DEFENDER_MENU',
    TOGGLE_DEFENDER_MENU: 'TOGGLE_DEFENDER_MENU',

    ENEMY_KILLED: 'ENEMY_KILLED',

    UPDATE_WAVE_STATS: 'UPDATE_WAVE_STATS',
    UPDATE_COINS: 'UPDATE_COINS',
    UPDATE_LIVES: 'UPDATE_LIVES',
    COINS_UPDATED: 'COINS_UPDATED',
    LIVES_UPDATED: 'LIVES_UPDATED',
};

export default Events;