const Events = {
    RESIZE: 'RESIZE',
    CHANGE_STATE: 'CHANGE_STATE',

    SPAWN_DEFENDER: 'SPAWN_DEFENDER',
    DESTROY_DEFENDER: 'DESTROY_DEFENDER',
    DEFENDER_COOLDOWN_START: 'DEFENDER_COOLDOWN_START',
    DEFENDER_COOLDOWN_COMPLETE: 'DEFENDER_COOLDOWN_COMPLETE',

    ENEMY_KILLED: 'ENEMY_KILLED',

    UPDATE_STATS: 'UPDATE_STATS',
    UPDATE_COINS: 'UPDATE_COINS',
    UPDATE_LIVES: 'UPDATE_LIVES',
};

export default Events;